from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

import numpy as np


FEMORA_PART_KIND_IDS = {
    "unknown": 0,
    "meshpart": 1,
    "interface": 2,
    "absorber": 3,
    "generated": 4,
}
FEMORA_PART_KIND_NAMES = {value: key for key, value in FEMORA_PART_KIND_IDS.items()}


@dataclass(frozen=True)
class FemoraPart:
    """Metadata entry for cells generated by one Femora source object."""

    tag: int
    kind: str
    kind_id: int
    name: str
    source_tag: int | None = None

    def to_dict(self) -> dict:
        return {
            "tag": self.tag,
            "kind": self.kind,
            "kind_id": self.kind_id,
            "name": self.name,
            "source_tag": self.source_tag,
        }


class FemoraPartRegistry:
    """Private model-owned registry for VTK cell source metadata.

    ``FemoraPartTag`` is a consecutive display tag used in cell data.
    ``FemoraPartKind`` is a small numeric enum used in cell data.
    The full tag-to-name/kind mapping is exported as VTK field data and JSON.
    """

    def __init__(self) -> None:
        self._parts: dict[tuple[str, str, int | None], FemoraPart] = {}
        self._next_tag = 1

    @staticmethod
    def kind_id(kind: str) -> int:
        normalized = str(kind).lower()
        if normalized not in FEMORA_PART_KIND_IDS:
            raise ValueError(
                f"Unknown Femora part kind '{kind}'. "
                f"Expected one of {sorted(FEMORA_PART_KIND_IDS)}."
            )
        return FEMORA_PART_KIND_IDS[normalized]

    def clear(self) -> None:
        self._parts.clear()
        self._next_tag = 1

    def get_or_create(
        self,
        *,
        kind: str,
        name: str,
        source_tag: int | None = None,
    ) -> FemoraPart:
        normalized_kind = str(kind).lower()
        kind_id = self.kind_id(normalized_kind)
        key = (normalized_kind, str(name), source_tag)
        part = self._parts.get(key)
        if part is not None:
            return part

        part = FemoraPart(
            tag=self._next_tag,
            kind=normalized_kind,
            kind_id=kind_id,
            name=str(name),
            source_tag=source_tag,
        )
        self._parts[key] = part
        self._next_tag += 1
        return part

    def get_all(self, used_tags: Iterable[int] | None = None) -> list[dict]:
        parts = sorted(self._parts.values(), key=lambda part: part.tag)
        if used_tags is not None:
            used = {int(tag) for tag in used_tags}
            parts = [part for part in parts if part.tag in used]
        return [part.to_dict() for part in parts]

    def build_snapshot(self, used_tags: Iterable[int] | None = None) -> dict:
        return {
            "femora_part_kinds": dict(FEMORA_PART_KIND_IDS),
            "femora_parts": self.get_all(used_tags=used_tags),
        }

    def attach_field_data(self, mesh, used_tags: Iterable[int] | None = None) -> None:
        parts = self.get_all(used_tags=used_tags)
        mesh.field_data["FemoraPartTags"] = np.asarray(
            [part["tag"] for part in parts],
            dtype=np.int32,
        )
        mesh.field_data["FemoraPartKindIds"] = np.asarray(
            [part["kind_id"] for part in parts],
            dtype=np.int16,
        )
        mesh.field_data["FemoraPartSourceTags"] = np.asarray(
            [part["source_tag"] if part["source_tag"] is not None else 0 for part in parts],
            dtype=np.int32,
        )
        mesh.field_data["FemoraPartNames"] = np.asarray(
            [part["name"] for part in parts],
            dtype=str,
        )
        mesh.field_data["FemoraPartKinds"] = np.asarray(
            [part["kind"] for part in parts],
            dtype=str,
        )
